language: php
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
php:
- '5.5'
- '5.6'
- '7.0'
- hhvm
- nightly
script: true
services:
- mysql
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  ./script/deploy.sh
